### ISSUE TITLE
Prepare presentation slides (due April 17)

### ISSUE THREAD

**Issue by elvisblanco1993** [elvisblanco1993/intern-hub#21]
This one is also due on April 17th.

**Comment by danieladebugs** [comment]
https://docs.google.com/presentation/d/194wtgdv7nsxvX7PWJm5La0ZxC1mg0Nghu6RQ5txRO00/edit?usp=sharing

**Comment by danieladebugs** [comment]
New link on SharePoint: https://fiudit-my.sharepoint.com/:p:/r/personal/eblan079_fiu_edu/Documents/Spring%202023/Capstone%20II/Sprints/Deliverable/InternHub%20Slides.pptx?d=w7a5fd1da451e4573bd74af05a53a43b2&csf=1&web=1&e=QB5Sod
